### ISSUE TITLE
iOS Rollbar integration, repo confusion and not seeing native crashes reporting.

### ISSUE THREAD

**Issue by pvandrunen** [emilyemorehouse/cordova-plugin-rollbar#2]
Hi @emilyemorehouse ,

I've been jumping around between blogs, docs, support and repo's trying to get a clear picture of which version/method of this plugin I'm supposed to be installing so that I can see native iOS crash reporting. 

I'm working on an ionic v1 project, javascript is working great 👍  but I'm not seeing crashes reported.  Here's what I've done thus far:

```bash
$ionic cordova plugin add https://github.com/emilyemorehouse/cordova-plugin-rollbar.git --variable ROLLBAR_ACCESS_TOKEN="<my token>" --variable ROLLBAR_ENVIRONMENT="production" --nofetch
```

```
$ionicPlatform.ready(function() {
    //Crash reporting
    window.cordova.plugins.Rollbar.init();

    //Trigger a crash 10 seconds after launch
    setTimeout(function(){
      window.cordova.plugins.Rollbar.simulateCrash();
    }, 10000);
});
```

**There are no error messages and the app DOES crash.**

ALSO, there is a version of the plugin with an 's', installation fails when I try to run 
```bash
ionic cordova plugin add https://github.com/emilyemorehouse/cordova-plugins-rollbar.git --variable ROLLBAR_ACCESS_TOKEN="<my token>" --variable ROLLBAR_ENVIRONMENT=“production”
```

I get this error message:
```
Failed to install 'cordova-plugin-rollbar': CordovaError: Uh oh!

"<Project folder>/plugins/cordova-plugin-rollbar/src/android/cordova/plugins/CDVRollbar.java" not found!
```

**Comment by emilyemorehouse** [comment]
Thanks for all the detailed info! You brought up a lot of great points, so bear with me!

## Project history/documentation/confusion
First off, the project has a bit of a fragmented past. I opted to create a clean, standalone repo and to leave my Resgrid fork archived [here](https://github.com/emilyemorehouse/cordova-plugins-rollbar). It was at that time that I opted to claim the 'cordova-plugin-rollbar' NPM package and to update the naming conventions to follow standard Cordova packages. That said, there's old blog posts I've written and documentation that apply to the old Resgrid package, or my fork of their package. I'm in the process of updating that info and will have it published on Rollbar's blog as soon as it's available.

From here on out, you can ditch all the plugin add commands that use the repo URL and just use the package name for the stable releases:
`cordova plugin add cordova-plugin-rollbar --variable ROLLBAR_ACCESS_TOKEN="<ROLLBAR_ACCESS_TOKEN>" --variable ROLLBAR_ENVIRONMENT="<ROLLBAR_ENVIRONMENT>"`

Cordova naming conventions use 'plugin' pretty much everywhere except for the clobber (the name of the window.XX variable that you interact with in your JS code), which is plural. Anything that deviates from this is probably from the old packages.

## Current crash not being reported
So it turns out that though the app is crashing, it's not a type of crash that gets reported. 

The good news is, I just pushed v1.3.0 of this package that has a successful crash that gets reported properly, so if you upgrade to that, you're good to go! I also added info in the README on testing crashes, so be sure to read that as well (dev environments don't report crashes).

**Comment by emilyemorehouse** [comment]
Let me know if this doesn't fix your issue and we can reopen this.

**Comment by pvandrunen** [comment]
Hi Emily, this update throws an error during build
```undefined symbols for architecture x86_64```

There's a pile of errors, I just think that's what the main error is?

**Comment by emilyemorehouse** [comment]
Hey @pvandrunen, your response got buried since I didn't reopen the issue. Sorry about that!

If you're still in need, I just published a new version that includes the Rollbar framework as a dependency instead of directly in the plugin. This fixed the `undefined symbols` error since it downloads the proper framework for your system.

Hope this helps!
